import { GoogleGenerativeAI } from '@google/generative-ai'

const genAI = new GoogleGenerativeAI(import.meta.env.VITE_GEMINI_API_KEY || '')

function getModel() {
  return genAI.getGenerativeModel({ model: 'gemini-2.0-flash' })
}

const isDemo = () => {
  const key = import.meta.env.VITE_GEMINI_API_KEY
  return !key || key === 'your_gemini_api_key_here' || key === ''
}

// ─── Smarter Mock Engine ──────────────────────────────────────────────────
const getMockResponse = (message: string, type: 'notes' | 'quiz' | 'chat') => {
  const msg = message.toLowerCase()
  
  if (type === 'chat') {
    if (msg.includes('machine learning')) {
      return `**Machine Learning (ML)** is a branch of AI that allows computers to learn from data without being explicitly programmed. 

Key concepts:
1. **Supervised Learning**: Training with labeled data (e.g., teaching a child with pictures).
2. **Unsupervised Learning**: Finding patterns in unlabeled data.
3. **Neural Networks**: Algorithms inspired by the human brain.

Would you like me to generate a **detailed note** or a **quiz** on this?`
    }
    if (msg.includes('photosynthesis')) {
      return `**Photosynthesis** is the process used by plants to convert light energy into chemical energy.

**The Formula:**
6CO2 + 6H2O + light energy → C6H12O6 + 6O2

Essentially, plants take in Carbon Dioxide and Water, use Sunlight as fuel, and produce Glucose (sugar) and Oxygen.`
    }
    if (msg.includes('newton') || msg.includes('laws of motion')) {
      return `**Newton's Three Laws of Motion** are the foundation of classical mechanics:

1. **Inertia**: An object at rest stays at rest unless a force acts on it.
2. **F = ma**: Force equals mass times acceleration.
3. **Action-Reaction**: For every action, there is an equal and opposite reaction.`
    }

    // Default "Smart" Chat fallback
    return `You asked about **"${message}"**. 

In simple terms, this topic is about understanding the fundamental mechanics of how things work in this field. It involves analyzing data, identifying patterns, and applying logic to solve problems.

**Quick Tip**: If you want to master this, try the **"AI Notes"** section in the sidebar to get a structured guide!`
  }

  if (type === 'notes') {
    return `
# Study Guide: **${message}**

## Overview
**${message}** is a vital part of modern education. It focuses on the core principles and how they apply to real-world scenarios.

## Key Takeaways
- **Concept A**: The basic foundation of the subject.
- **Concept B**: How different variables interact.
- **Concept C**: Practical implementation and results.

---
*Generated by Cognify Neural Engine (Demo Mode)*
`
  }

  // Quiz Fallback
  return [
    { question: `What is a primary characteristic of ${message}?`, options: ["Logic-driven", "Randomness", "No structure", "Manual only"], correctAnswer: 0, explanation: "Most educational topics are built on systematic logic." },
    { question: `Which of these is used in ${message}?`, options: ["Data analysis", "Guessing", "Coin flip", "None"], correctAnswer: 0, explanation: "Data analysis is key to understanding complex subjects." }
  ]
}

export async function generateNotes(topic: string, difficulty: any, language: any): Promise<string> {
  if (isDemo()) return getMockResponse(topic, 'notes') as string
  const model = getModel()
  const result = await model.generateContent(`Generate notes for ${topic}. Difficulty: ${difficulty}, Lang: ${language}. Markdown.`)
  return result.response.text()
}

export async function generateQuiz(topic: string, numQuestions: number = 5): Promise<any[]> {
  if (isDemo()) return getMockResponse(topic, 'quiz') as any[]
  const model = getModel()
  const result = await model.generateContent(`Generate ${numQuestions} MCQs for ${topic}. Raw JSON array only.`)
  const text = result.response.text().trim().replace(/```json\n?/g, '').replace(/```\n?/g, '').trim()
  return JSON.parse(text)
}

export async function chatWithAI(message: string, chatHistory: any[], simplify: boolean = false): Promise<string> {
  if (isDemo()) return getMockResponse(message, 'chat') as string
  const model = getModel()
  const result = await model.generateContent(`Cognify AI Tutor. User: ${message}. ${simplify ? 'Explain like 10yo' : ''}`)
  return result.response.text()
}

export async function generateFeedback(name: string, scores: number[], topics: string[]): Promise<string> {
  if (isDemo()) return `Great job, ${name}!`
  const model = getModel()
  const result = await model.generateContent(`Feedback for ${name}. Topics: ${topics.join(',')}`)
  return result.response.text()
}
