import { motion, useInView } from 'framer-motion'
import { useRef } from 'react'

interface Feature {
  icon: string
  title: string
  description: string
  colorClass: string
}

const features: Feature[] = [
  {
    icon: '📝',
    title: 'AI-Powered Notes',
    description:
      'Upload any material and get beautifully structured, concise notes generated by AI — tailored to your learning style.',
    colorClass: 'feature-icon-wrapper--purple',
  },
  {
    icon: '🧠',
    title: 'Adaptive Quizzes',
    description:
      'Automatically generated quizzes that adapt to your knowledge gaps, reinforcing weak areas and tracking your progress.',
    colorClass: 'feature-icon-wrapper--blue',
  },
  {
    icon: '💬',
    title: 'Smart AI Tutor',
    description:
      'An intelligent chatbot that explains concepts, answers questions, and guides your learning journey 24/7.',
    colorClass: 'feature-icon-wrapper--cyan',
  },
  {
    icon: '📊',
    title: 'Progress Analytics',
    description:
      'Visual dashboards that track your study habits, quiz scores, and learning velocity with actionable insights.',
    colorClass: 'feature-icon-wrapper--green',
  },
]

const containerVariants = {
  hidden: {},
  visible: {
    transition: {
      staggerChildren: 0.12,
    },
  },
}

const cardVariants = {
  hidden: { opacity: 0, y: 40 },
  visible: {
    opacity: 1,
    y: 0,
    transition: {
      duration: 0.6,
      ease: [0.22, 1, 0.36, 1],
    },
  },
}

const headerVariants = {
  hidden: { opacity: 0, y: 30 },
  visible: {
    opacity: 1,
    y: 0,
    transition: {
      duration: 0.7,
      ease: [0.22, 1, 0.36, 1],
    },
  },
}

export default function Features() {
  const ref = useRef<HTMLElement>(null)
  const isInView = useInView(ref, { once: true, margin: '-100px' })

  return (
    <section className="features-section" id="features" ref={ref}>
      <div className="container">
        {/* Header */}
        <motion.div
          className="features-header"
          variants={headerVariants}
          initial="hidden"
          animate={isInView ? 'visible' : 'hidden'}
        >
          <div className="section-eyebrow">Features</div>
          <h2 className="section-title">
            Everything you need to<br />
            master any subject
          </h2>
          <p className="section-subtitle">
            Cognify combines cutting-edge AI with proven learning science
            to deliver a study experience that actually works.
          </p>
        </motion.div>

        {/* Cards */}
        <motion.div
          className="features-grid"
          variants={containerVariants}
          initial="hidden"
          animate={isInView ? 'visible' : 'hidden'}
        >
          {features.map((feature) => (
            <motion.div
              key={feature.title}
              className="feature-card"
              variants={cardVariants}
              whileHover={{
                y: -6,
                boxShadow: '0 0 80px rgba(124, 58, 237, 0.2)',
                borderColor: 'rgba(255,255,255,0.15)',
              }}
            >
              <div className="feature-card-content">
                <div className={`feature-icon-wrapper ${feature.colorClass}`}>
                  <span role="img" aria-label={feature.title}>
                    {feature.icon}
                  </span>
                </div>
                <h3 className="feature-title">{feature.title}</h3>
                <p className="feature-description">{feature.description}</p>
              </div>
            </motion.div>
          ))}
        </motion.div>
      </div>
    </section>
  )
}
